"""Compatibility shim for legacy imports.

Deprecated: import from `src.models.models` directly.
"""

from src.models.models import (
	ABAssignmentModel,
	ABExperimentModel,
	ABResultModel,
	ABVariantModel,
	AllowedContact,
	Appointment,
	AuditLog,
	Base,
	BusinessConfig,
	CalendarCredential,
	ChatCounter,
	ChatProfile,
	ChatStrategy,
	Contact,
	Conversation,
	ConversationMessage,
	ConversationObjective,
	ConversationProfile,
	DailyContext,
	HumanizationMetric,
	ModelConfig,
	Prompt,
	Rule,
	SilentTransfer,
	UserContext,
)

__all__ = [
	"ABAssignmentModel",
	"ABExperimentModel",
	"ABResultModel",
	"ABVariantModel",
	"AllowedContact",
	"Appointment",
	"AuditLog",
	"Base",
	"BusinessConfig",
	"CalendarCredential",
	"ChatCounter",
	"ChatProfile",
	"ChatStrategy",
	"Contact",
	"Conversation",
	"ConversationMessage",
	"ConversationObjective",
	"ConversationProfile",
	"DailyContext",
	"HumanizationMetric",
	"ModelConfig",
	"Prompt",
	"Rule",
	"SilentTransfer",
	"UserContext",
]
