"""Add last_reply_at to chat_counters

Revision ID: 7ff5fb627e60
Revises: 
Create Date: 2025-09-22 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff5fb627e60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_counters', sa.Column('last_reply_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_counters', 'last_reply_at')
    # ### end Alembic commands ###